config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/sign_up', to: 'static_pages#sign_up'
  get '/login', to: 'static_pages#login'

  resources :signboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  belongs_to :signboard
end

app/models/signboard.rb
class Signboard < ApplicationRecord
  has_many :artists
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_signboard
  before_action :set_artist, except: [:index, :new, :create]

  def index
    @artists = @signboard.artists.all
  end

  def show
  end

  def new
    @artist = @signboard.artists.new
  end

  def create
    @artist = @signboard.artists.new(artist_params)
    if @artist.save
      redirect_to signboard_artist_path(@signboard, @artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to signboard_artist_path(@signboard, @artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to signboard_artists_path(@signboard)
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :genre, :rating)
    end

    def set_artist
      @artist = @signboard.artists.find(params[:id])
    end

    def set_signboard
      @signboard = Signboard.find(params[:signboard_id])
    end
end

app/controllers/signboards_controller.rb
class SignboardsController < ApplicationController
  before_action :set_signboard, except: [:index, :new, :create]

  def index
    @signboards = Signboard.all
  end

  def show
  end

  def new
    @signboard = Signboard.new
  end

  def create
    @signboard = Signboard.new(signboard_params)
    if @signboard.save
      redirect_to signboard_path(@signboard)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @signboard.update(signboard_params)
      redirect_to signboard_path(@signboard)
    else
      render :edit
    end
  end

  def destroy
    @signboard.destroy
    redirect_to :index
  end

  private
    def signboard_params
      params.require(:signboard).permit(:name, :total)
    end

    def set_signboard
      @signboard = Signboard.find(params[:id])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, except: [:index, :new, :create]

  def index
    @songs = @artist.songs.all
  end

  def show
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private
    def song_params
      params.require(:song).permit(:album, :title, :release_date)
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = @artist.songs.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def sign_up
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/signboards_helper.rb
module SignboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/artists/_form.html.erb
<div class='container'>
  <%= form_for [@signboard, @artist] do |f| %>
    <div class='col m6'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='col m6'>
      <%= f.label :genre %>
      <%= f.text_field :genre %>
    </div>
    <div class='col m6'>
      <%= f.label :rating %>
      <%= f.number_field :rating, min: 0, max: 10 %>
    </div>
    <%= f.submit class: 'btn white black-text' %>
  <% end %>
</div>

app/views/artists/edit.html.erb
<h1 class='center'><%= @artist.name.pluralize %> </h1>
<hr/>
<%= render 'artists/form' %>
<br />
<h6 class='center'>
  <%= link_to 'Delete', signboard_artist_path(@signboard, @artist) %>
</h6>

app/views/artists/index.html.erb
<h1 class='center'>
  Artists for <%= @signboard.name.pluralize %> Top <%= @signboard.total %>
</h1>
<div class='center'>
<%= link_to 'Add Artist', new_signboard_artist_path, class:'btn black white-text' %>
</div>

<p>Name --  Genre -- Rating</p>
<ul class='collection'>
  <% @artists.each do |artist| %>
    <li class='collection-item'>
      <a>
        <%= link_to artist.name, signboard_artist_path(@signboard, artist) %>
      </a>
      <a>
        <%= link_to artist.genre, signboard_artist_path(@signboard, artist) %>
      </a>
      <a>
        <%= link_to artist.rating, signboard_artist_path(@signboard, artist) %>
      </a>
      <a class='right'>
        <%= link_to 'Edit', edit_signboard_artist_path(@signboard, artist) %>
      </a>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1 class='center'>Make an Artist</h1>

<%= render 'artists/form' %>

app/views/artists/show.html.erb
<h1 class='center'> <%= @artist.name %> </h1>
<h4 class='center'><%= @artist.genre %> <%= @artist.rating %></h4>

<h6 class='center'><%= link_to 'Add a Song', artist_songs_path(@signboard, @artist) %></h6>

app/views/layouts/_navbar.html.erb
<nav class='blue darken-2'>
  <div class='nav-wrapper'>
    <ul class='right'>
      <li><a href='/'>Home</a></li>
      <li><a href='/help'>Help</a></li>
      <li><a href='/sign_up'>Sign Up</a></li>
      <li><a href='/login'>Login</a></li>
    </ul>
    <ul class='left'>
      <li><a href='/signboards'>Billboards</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class='container'>
    <%= render '/layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/signboards/_form.html.erb
<div class='container'>
  <%= form_for @signboard do |f| %>
    <div class='col m6'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='col m6'>
      <%= f.label :total %>
      <%= f.number_field :total, min: 0, max: 25 %>
    </div>
    <%= f.submit class: 'btn white black-text' %>
  <% end %>
</div>

app/views/signboards/edit.html.erb
<h1 class='center'><%= @signboard.name.pluralize %> </h1>
<h4 class='center'> Top <%= @signboard.total %> </h4>
<hr />
<%= render 'signboards/form' %>
<br />
<br />
<h6 class='center'> <%= link_to 'Delete', signboard_path(@signboard) %> </h6>

app/views/signboards/index.html.erb
<h1 class='center'>Billboards</h1>
<div class='center'>
<%= link_to 'Add Billboard', new_signboard_path, class:'btn black white-text' %>
</div>

<p>Name -- Total</p>
<ul class='collection'>
  <% @signboards.each do |signboard| %>
    <li class='collection-item'>
      <a><%= link_to signboard.name.pluralize, signboard_path(signboard) %></a>
      <a> Top <%= link_to signboard.total, signboard_path(signboard) %></a>
      <div class='right'>
      <a><%= link_to 'Edit', edit_signboard_path(signboard) %></a>
      </div>
    </li>
  <% end %>
</ul>

app/views/signboards/new.html.erb
<h1 class='center'>Make a Billboard</h1>

<%= render 'signboards/form' %>

app/views/signboards/show.html.erb
<h1 class='center'> <%= @signboard.name.pluralize %> </h1>
<h4 class='center'> Top <%= @signboard.total %> </h4>

<h6 class='center'><%= link_to 'Add an Artist', signboard_artists_path(@signboard) %></h6>

app/views/songs/_form.html.erb
<div class='container'>
  <%= form_for [@signboard, @artist, @song] do |f| %>
    <div class='col m6'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='col m6'>
      <%= f.label :album %>
      <%= f.text_field :album %>
    </div>
    <div class='col m6'>
      <%= f.label :release_date %>
      <%= f.date_field(:release_date) %>
    </div>
    <%= f.submit class: 'btn white black-text' %>
  <% end %>
</div>

app/views/songs/edit.html.erb
<h1 class='center'><%= @song.title %> </h1>
<hr/>
<%= render 'songs/form' %>
<br />
<h6 class='center'>
  <%= link_to 'Delete', artist_song_path(@artist, @song) %>
</h6>

app/views/songs/index.html.erb
<h1 class='center'>
  Songs for <%= @artist.name.pluralize %>
</h1>
<div class='center'>
<%= link_to 'Add Song', new_artist_song_path, class:'btn black white-text' %>
</div>

<p>Title --  Album -- Release Date</p>
<ul class='collection'>
  <% @songs.each do |song| %>
    <li class='collection-item'>
      <a>
        <%= link_to song.title, artist_song_path(@artist, song) %>
      </a>
      <a>
        <%= link_to song.album, artist_song_path(@artist, song) %>
      </a>
      <a>
        <%= link_to song.release_date, artist_song_path(@artist, song) %>
      </a>
      <a class='right'>
        <%= link_to 'Edit', edit_artist_song_path(@artist, song) %>
      </a>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1 class='center'>Add a Song</h1>

<%= render 'songs/form' %>

app/views/songs/show.html.erb
<h1 class='center'><%= @song.title %></h1>
<h4 class='center'><%= @song.album %> <%= @song.release_date %></h4>

<h6 class='center'><%= link_to 'Artist', signboard_artists_path(@artist, @song) %> </h6>

app/views/static_pages/help.html.erb
<h1 class='center purple-text'>You need Help?</h1>
<br />
<p class='center red-text'>Go look on Google</p>

app/views/static_pages/home.html.erb
<h1 class='center red-text'>Welcome to Music</h1>
<hr/ >

app/views/static_pages/login.html.erb
<h1>StaticPage#login</h1>
<p>Find me in app/views/static_page/login.html.erb</p>

app/views/static_pages/sign_up.html.erb
<h1>StaticPage#sign_up</h1>
<p>Find me in app/views/static_page/sign_up.html.erb</p>